### ISSUE TITLE
Swift 3 release process

### ISSUE THREAD

**Issue by ilyapuchka** [AliSoftware/Dip#109]
The current plan as I imagine it is following.

Before Swift 3 is released (probably the end of this week or next week) we can make a prerelease (4.6.1 or maybe better 4.7?) with some API naming improvements ( #105 ). That will let to migrate to new APIs (that are more inline with api guidelines) earlier without source breaking changes and have less headache when migrating to Swift 3.

When Swift 3 is released we will make a new major release 5.0. At this point `swift3` branch will be merged to develop and all further development will happen in Swift 3.  At the same time we will create new branch `swift2.3` that will contain all the same features but will be built with Swift 2.3. Each new release will be provided with binaries built with Swift 3 and Swift 2.3. (not sure how Carthage will handle that, maybe it will load all binaries, maybe none of them). After some reasonable time `swift2.3` branch will be deprecated and no longer supported.

Dip 5.0 will aslo contain some breaking changes (like #71 ) and previously deprecated APIs will be removed.

@AliSoftware does it sound good to you?

**Comment by jeffdav** [comment]
+1

**Comment by mark-urbanthings** [comment]
What's the timescale for this now that Xcode 8 / Swift 3 GM available to developers ?

**Comment by ilyapuchka** [comment]
Was planing to wrap up release this weekend

**Comment by mark-urbanthings** [comment]
Perfect !

**Comment by mark-urbanthings** [comment]
Heads up you may have problems pushing to cocoapods. See https://github.com/CocoaPods/CocoaPods/pull/5650 - I've not found a work around yet :-(

**Comment by vCrespoP** [comment]
+1

**Comment by ilyapuchka** [comment]
5.0.0 is pushed to trunk! 🎉
