### ISSUE TITLE
Single Dip target causing problems

### ISSUE THREAD

**Issue by mark-urbanthings** [AliSoftware/Dip#133]
I've just moved from Xcode 7 / Swift 2.2 to Xcode 8 / Swift 2.3 and Dip is used within app, extension and watch app. In the 2.2 compatible Dip variant the project had separate targets for each platform (iOS, watchOS, tvOS and macOS). The 2.3 variant now has a single Dip target. This seems to be causing issues when you have multiple components for different platforms using Dip within the same project / workspace.

To get my project both build and archive I had to take the 2.2 Dip project file and drop in the 2.3 source files. Without this building my project doesn't appear to build for both iOS and watchOS and then fails since the instance of Dip that is found doesn't support the platform being compiled.

The combined target approach is new to me so maybe there is something that can be done to get it to work but I've not managed to figure it out.

Maybe I can setup a simple project that reproduces this tomorrow, but if you have any comments in the meantime or a solution that would be great ! Note that I'm not using CocoaPods or Carthage but just have Dip pulled with git and added to my project / workspace.

**Comment by ilyapuchka** [comment]
Hi @mark-urbanthings. For now I can only suggest to include Dip source files to your target instead of using it as a sub project, if that is how you link it. To investigate the issue I will need some time. Sample project will help a lot.

**Comment by mark-urbanthings** [comment]
I don't want to include source files directly since there are multiple frameworks + app, extension and watch app using Dip within our project. However I have a work around for now based on reverting the Dip project to per-platform targets. I'll try and get you something that reproduces the issue tomorrow.

**Comment by mark-urbanthings** [comment]
[DipIssue.zip](https://github.com/AliSoftware/Dip/files/537157/DipIssue.zip)
Actually was very simple to reproduce issue. If you build this for simulator you'll find that it builds Dip for iOS but not Dip for watchOS even though there is a requirement for this since Dip is embedded in the watch app as well as the iOS app. Also when you embed Dip its only listed as Dip macOS so you can't actually specify platform when selecting Dip to be embedded. When there were separate build targets this worked and when you embedded Dip into watch app or iOS app you were able to select Dip watchOS or Dip iOS as appropriate. Maybe just going back to separate targets is the answer?

**Comment by ilyapuchka** [comment]
To be honest it looks like Xcode issue for me. If you first build Dip for ios and watchos and then build dependent target there will be no error.
The other problem is that when we use subproject Xcode shows that dependent target can be also built for all platforms, what is simply wrong. That does not happen if you use workspace.
With workspace you will also need to build Dip first for ios and watch os.

You can solve that by adding custom script that will build Dip for proper target.

In DipIssue build phases add
```
xcodebuild -workspace DipIssue.xcworkspace -scheme Dip -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' ONLY_ACTIVE_ARCH=NO
```
In DipWatchIssue build phases add
```
xcodebuild -workspace DipIssue.xcworkspace -scheme Dip -sdk watchsimulator -destination 'platform=watchOS Simulator,name=Apple Watch - 38mm,OS=latest' ONLY_ACTIVE_ARCH=NO
```
These are almost the same commands used to build Dip on Travis.

Will this (switching to workspace + adding custom script) work for you as a fix? And why don't you consider using Carthage or CocoaPods?

**Comment by mark-urbanthings** [comment]
The build script step and workspace should work for us. The actual project is built from a workspace already but as you indicate you still need to build both Dip platforms manually first. This doesn't work for 'Archive' build since that always starts from clean state. The script step will fix that though. We are looking to move the whole project to CocoaPods including a private repo for internal components but so far have hit issues with it that are not yet resolved (Xcode 8 related + pod tramping on .git/config of project when publishing to private repo). Carthage was also used early on but it was painfully slow to build whenever we changed internal components (talking factor of 10-20 over building outside Carthage, something to do with how it pipes and processes the build transcript I believe). That made builds time unacceptable when part of code / build / debug cycle. Will either use CocoaPods if the issues get resolved of build our own set of scripts to pull everything together ! Anyway thanks for great piece of software and taking the time to look into this.

**Comment by ilyapuchka** [comment]
Fell free to reopen if script build step will not work
