### ISSUE TITLE
Swift 2.3 changes breaks some APIs

### ISSUE THREAD

**Issue by tapsandswipes** [AliSoftware/Dip#134]
Compiling for 2.3 gives errors related to API differences.

For example:

```container.resolve(tag: "tag", arguments: arg1, arg2)```

in 2.3 must be now changed into:

```container.resolve("tag", arguments: arg1, arg2)```

This was not happening on previous Dip versions compatible with 2.3

**Comment by ilyapuchka** [comment]
Thanks for spotting that. I'll fix it and release 5.0.4 shortly.

**Comment by ilyapuchka** [comment]
@tapsandswipes please upgrade to 5.0.4 and thanks again for reporting the issue
