### ISSUE TITLE
Mixing implicit and runtime arguments

### ISSUE THREAD

**Issue by danielsaidi** [AliSoftware/Dip#136]
Hi!

Thank you so much for Dip - I love using it.

I am however struggling a bit with how to mix argument types, where most arguments should be implicitly registered (by the bootstrapper), but one should be set in runtime.

To clarify, say that I have a view controller with the following initializer:

```
init(
   service: MyService) {
   self.service = service
   super.init(nibName: type(of: self).className, bundle: nil)
}
```

I register the vc like this:

```
dip.register { MyViewController(
   service: $0)
   as MyViewController 
}
```

When resolving, I just call dip's `resolve` function and everything's dandy.

However, let's consider that the view controller would also require an object, but a dynamic one that has to be set in runtime. If I use the setup above, I would have to resolve the view controller, then set the object through a public property...but that would force me to make this mandatory object optional or implicitly unwrapped as well as exposing it, which I may not want to do.

Dip allows you to register your types with runtime arguments, but if I try to register the object dependency like this:

```
dip.register { (obj: MyObject) MyViewController(
   service: $0,
   obj: obj)
   as MyViewController
}
```

I get the following error:

```Anonymous closure arguments cannot be used inside a closure that has explicit arguments.```

The examples do not show how you achieve this. Any ides?

Thanks in advance!

**Comment by ilyapuchka** [comment]
Hi, @danielsaidi. 
In closures you can not mix two styles of referencing its arguments - using explicit names and anonymous arguments (with `$`). Using anonymous arguments is just a shorthand that is convenient when you are using auto-wiring, with you are just relying on type inference. But it is not required to resolve components.

To achieve what you want you may use this:

```swift
dip.register { (obj: MyObject) try MyViewController(
   service: container.resolve(),
   obj: obj)
   as MyViewController
}
```

**Comment by danielsaidi** [comment]
Hi @ilyapuchka 

Thanks for your super-fast response.

yeah, I realized that this was what I had to do. I can confirm that it works great 👍 

Thank you!
