### ISSUE TITLE
Can I auto-inject without registering?

### ISSUE THREAD

**Issue by sergthedeveloper** [AliSoftware/Dip#137]
Hi @ilyapuchka 

Is it possible to process auto-injections without registering the instance which is not designed to be registered. Like the following:

```swift
class Target {
    var prop: Injected<Prop>
    var weakProp: InjectedWeak<Prop>
}


let container = DependencyContainer()
// ...
let target = Target()
container.injectTo(target)
```

First workaround that come to mind:

```swift
let target = Target()
let def = container.register { target }
try! container.resolve() as Target
container.remove(def)

```

Second (partially copy-pasted from AutoInjection.swift)

```swift
let target = Target()
for child in Mirror(reflecting: target).children {
    if let injectedPropertyBox = child.value as? AutoInjectedPropertyBox {
        injectedPropertyBox.resolve(container)
    }
}
```

BTW, thanks for your work and this awesome library!

**Comment by ilyapuchka** [comment]
Hi, @sergthedeveloper. As auto-injection is a step of *resolve* process that means that there should be registered definition for that type, and there is currently no public api to inject into objects created not by the container. One of the reasons for that is that in case of circular dependencies when auto-injected property should reference the instance that holds it (like when you use a delegate pattern that is very usual) it will be not satisfied if you don't register both objects.

Is there any serious concern that makes you to avoid registering that `Target` object in the container?

**Comment by sergthedeveloper** [comment]
No reason except that `Target` is not going to be injected itself. 
So it shouldn't cause circular dependency problem in this particular case.
Anyway, it's not a real serious problem for me,  just a question, and I definitely going to try Dip in my project.
