### ISSUE TITLE
Auto-Injection warnings

### ISSUE THREAD

**Issue by ArtFeel** [AliSoftware/Dip#139]
Hi, I'm new to Swift, maybe I'm doing something wrong, but in Wiki, there is the same code example
```swift
private let injectedApiClient = Injected<APIClient>()
var apiClient: APIClient? { return injectedApiClient.value }
```
But, when I'm doing like this, I received warnings:
```
Warning:(22, 20) expression implicitly coerced from 'APIClient?' to Any
Note:(22, 20) provide a default value to avoid this warning
Note:(22, 20) force-unwrap the value to avoid this warning
Note:(22, 20) explicitly cast to Any with 'as Any' to silence this warning
```

**Comment by ilyapuchka** [comment]
Never saw these warnings. What version of Xcode do you use?

**Comment by ilyapuchka** [comment]
I guess it has something to do with this bug https://bugs.swift.org/browse/SR-2921

**Comment by ArtFeel** [comment]
Sorry, this bug appears only in AppCode, I think I should fill a bug report. In XCode 8.1 everything is ok.
