### ISSUE TITLE
Does Dip support objective-c?

### ISSUE THREAD

**Issue by oronbz** [AliSoftware/Dip#140]
I haven't seen anything on the documentation or issues referring this.

**Comment by ilyapuchka** [comment]
No, sorry, Dip is designed only for Swift.

**Comment by oronbz** [comment]
If i create the container in swift, will it be able to do constructor initialization to objective c classes?

**Comment by ilyapuchka** [comment]
Yes, as long as they are visible for Swift code. But the container itself you can use only from Swift code.
