### ISSUE TITLE
Auto resolve Closures which return Registered Types

### ISSUE THREAD

**Issue by sai-prasanna** [AliSoftware/Dip#142]
Hey, Dip is amazing, and I think its the best DI framework there for swift.

I found that one can register closures types in Dip, naturally I was wondering whether something like this is possible.

``` swift
struct AType {
    let service: String
    let runtime: Int
}

struct BType {
    let aCreator: (Int) -> AType
    let service: String
}
```

Suppose I do this

``` swift
let container = DependencyContainer() { c in
    c.register() {
        "Hello" // This resolves to x as its only string registered
    }
    c.register() {
        AType(service: $0, runtime: $1) // as we don't have runtime Int registered we can resolve it as runtime argument
    }
    c.register() {
        BType(aCreator: $0, service: $1) // This fails as $0 is a closure type which is not registered
    }
}
```

Can we make closures that return a registered type to auto resolve as closures taking runtime arguments?

I mean 

> (Int) -> AType 

should auto resolve to 

``` swift
 { (a: Int) in try! c.resolve(argument: a) as AType  }
```
That is if we don't find a closure type registered in container, we check return type of closure, and resolve with arguments for inputs of the closure. 

I haven't dived into Mirror yet, so if you think this is possible, I will look into it and give a pull request, or atleast write a extension for personal use. :)

**Comment by ilyapuchka** [comment]
When you are registering closure that accepts two parameters it will be registered so that you will be able to resolve it using exactly the same two parameters. Or now parameters at all, then container will try to auto-wire all the dependencies resolving them using inferred types. But you will not be able to resolve it with only one parameter. Allowing that will make implementation too complicated and can even affect performance, as we will need to check all possible combinations of parameters. If I understood correctly what you want

**Comment by sai-prasanna** [comment]
@ilyapuchka  I don't understand.

I want a way  to resolve closures that return registered types to auto resolve using registered factories with the input args of closure as runtime arguments.

I tried mirroring a closure, but cant get Input types and return types from the mirror. If I can get that, this becomes trivial I think

**Comment by sai-prasanna** [comment]
Sorry I botched up the example , while trying I did something like this 

``` swift
c.register() {
      { (a: Int) in try! AType(service: $0, runtime: a)  }
 }
```

But also assumed  this would work

``` swift
 c.register() {
    { (a: Int) in try! c.resolve(arguments: a) as AType }
 }
```

**Comment by sai-prasanna** [comment]
@ilyapuchka  

Suppose I do this 

``` swift
c.register() {
        AType(service: c.resolve(), runtime: $1)
  }
```

Now would it be possible to auto resolve closures?

**Comment by ilyapuchka** [comment]
These two closures have different types as you are not using $0 in the second one, so it's type is `() -> (Int) -> AType`, and the type of first is `(String) -> (Int) -> AType`

**Comment by ilyapuchka** [comment]
If you register AType like this then you will be able to resolve it with `resolve(arguments: Int)`. Then if you register closure as `register() { { (a: Int) try! resolve(arguments: a) as AType }}` you will be able to resolve closure with `resolve() as (Int) -> AType`.

**Comment by sai-prasanna** [comment]
Yeah got it. Will check docs, and if you want give a pull request making it clear that partial arguments are not resolved.

Now to the matter at hand, if a factory returning X is registered with runtime args (A1, A2) , would it be possible to resolve (A1, A2) -> X automatically ?

**Comment by ilyapuchka** [comment]
so you want something like this
 
```swift
container.register() { (a1: A1, a2: A2) in X(a1: a1, a2: a2) }
let closure = container.resolve() as (A1, A2) -> X
```

right?

**Comment by sai-prasanna** [comment]
Exactly, if { (A1, A2) -> X } is not explicitly registered, then just registering X as you did should resolve the factory?

This helps in assisted injection pattern , without factories or interfaces or anything. And eliminating the need to explicitly register would help autowiring. Or Am I being too lazy?

**Comment by sai-prasanna** [comment]
I found a way, thanks a lot for the help. It clarified what I wanted to do.

``` swift
extension DependencyContainer {
    @discardableResult public func registerWithFactory<T, A>(_ scope: ComponentScope = .shared, type: T.Type = T.self, tag: DependencyTagConvertible? = nil, factory: @escaping (A) throws -> T) -> Definition<T, A> {
        
        unowned let container = self
        register(scope, tag: tag) {
            { (a: A) in try! container.resolve(arguments: a) as T }
        }
        
        
        return register(scope: scope, type: type, tag: tag, factory: factory, numberOfArguments: 1) { container, tag in try factory(container.resolve(tag: tag)) }
    }
}
```

btw Any hope of swift supporting variadic Generics?

**Comment by ilyapuchka** [comment]
Yes, that's basically what you need to do. Not sure if it make sense to do it implicitly every time for any number of arguments. I haven't heard anything about variadic generics being discussed in swift evolution.

**Comment by sai-prasanna** [comment]
Here is one I found in swift evolution :- https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20160530/019766.html
