### ISSUE TITLE
Memory issue, registering classes.

### ISSUE THREAD

**Issue by njall1** [AliSoftware/Dip#159]
Registering classes have memory issue:
![screen shot 2017-05-19 at 11 03 20](https://cloud.githubusercontent.com/assets/9320927/26238651/9e8c9024-3c82-11e7-8246-d50ccb079ad5.png)

```swift
import Dip

let rootAssembly = DependencyContainer { (container) in
    unowned let container = container
    
    container.register(.weakSingleton, factory: RootPresenter.init)
        .implements(AnyObject.self,
                    RootModuleInput.self,
                    AppDelegateOutput.self,
                    RootInteractorOutput.self)
        .resolvingProperties { container, presenter in
            presenter.delegate = UIApplication.shared.delegate as! AppDelegate
            presenter.router = try! container.resolve()
            presenter.interactor = try! container.resolve()
            presenter.deeplinkHandler = try! container.resolve()
            presenter.shortcutHandler = try! container.resolve()
    }
...
```
or

```swift
import Dip

let rootAssembly = DependencyContainer { (container) in
    unowned let container = container
    
    container.register(.weakSingleton, type: RootPresenter.self, factory: RootPresenter.init)
        .implements(AnyObject.self,
                    RootModuleInput.self,
                    AppDelegateOutput.self,
                    RootInteractorOutput.self)
        .resolvingProperties { container, presenter in
            presenter.delegate = UIApplication.shared.delegate as! AppDelegate
            presenter.router = try! container.resolve()
            presenter.interactor = try! container.resolve()
            presenter.deeplinkHandler = try! container.resolve()
            presenter.shortcutHandler = try! container.resolve()
    }
...
```
or 

```swift
import Dip

let rootAssembly = DependencyContainer { (container) in
    unowned let container = container
    
    container.register(.weakSingleton) { RootPresenter() }
        .implements(AnyObject.self,
                    RootModuleInput.self,
                    AppDelegateOutput.self,
                    RootInteractorOutput.self)
        .resolvingProperties { container, presenter in
            presenter.delegate = UIApplication.shared.delegate as! AppDelegate
            presenter.router = try! container.resolve()
            presenter.interactor = try! container.resolve()
            presenter.deeplinkHandler = try! container.resolve()
            presenter.shortcutHandler = try! container.resolve()
    }
```

I've fixed issue by this way: 
![screen shot 2017-05-19 at 11 09 50](https://cloud.githubusercontent.com/assets/9320927/26238869/8dc42850-3c83-11e7-868a-97f865e790cc.png)

```swift
import Dip

let rootAssembly = DependencyContainer { (container) in
    unowned let container = container
    
    container.register(.weakSingleton, type: RootModuleInput.self, factory: RootPresenter.init)
        .implements(AnyObject.self,
                    AppDelegateOutput.self,
                    RootInteractorOutput.self)
        .resolvingProperties { container, presenter in
            presenter.delegate = UIApplication.shared.delegate as! AppDelegate
            presenter.router = try! container.resolve()
            presenter.interactor = try! container.resolve()
            presenter.deeplinkHandler = try! container.resolve()
            presenter.shortcutHandler = try! container.resolve()
    }
...
```

or

```swift
    container.register(.weakSingleton) { RootPresenter() as RootModuleInput }
        .implements(AnyObject.self,
                    AppDelegateOutput.self,
                    RootInteractorOutput.self)
        .resolvingProperties { container, presenter in
            presenter.delegate = UIApplication.shared.delegate as! AppDelegate
            presenter.router = try! container.resolve()
            presenter.interactor = try! container.resolve()
            presenter.deeplinkHandler = try! container.resolve()
            presenter.shortcutHandler = try! container.resolve()
    }
...
```

Also issue actual for scopes : shared, singleton, eagerSingleton, weakSingleton.

Please provide any solution, because for me very important registering classes not protocols.

**Comment by sc0rch** [comment]
Move rootAssembly to Application delegate class.
It will fix the most of problems.

**Comment by njall1** [comment]
I checked this way and it has not helped.
![screen shot 2017-05-19 at 11 28 35](https://cloud.githubusercontent.com/assets/9320927/26239582/4df4c72c-3c86-11e7-8263-b3bf329d69b9.png)

import Dip

class AppDelegate: UIResponder, UIApplicationDelegate, AppDelegateInput {

    var window: UIWindow?
    var serviceLocator: ServiceLocator?
    
    var output: AppDelegateOutput?
    var moduleInput: RootModuleInput?
    
//    let container: DependencyContainer = rootAssembly
    
    let container = DependencyContainer { (container) in
        unowned let container = container
        
        container.register(.weakSingleton) { RootPresenter() }
            .implements(AnyObject.self,
                        RootModuleInput.self,
                        AppDelegateOutput.self,
                        RootInteractorOutput.self)
            .resolvingProperties { container, presenter in
                presenter.delegate = UIApplication.shared.delegate as! AppDelegate
                presenter.router = try! container.resolve()
                presenter.interactor = try! container.resolve()
                presenter.deeplinkHandler = try! container.resolve()
                presenter.shortcutHandler = try! container.resolve()
        }
...

**Comment by ilyapuchka** [comment]
Can you please state the problem more clear? What is expected, what is actual behaviour?

**Comment by njall1** [comment]
Expected: 
If you register a class with the scope: weakSingleton, there must be one instance of this class in memory.

Actual behaviour: 
I've registered class with scope: weakSingleton

    let container = DependencyContainer { (container) in
        unowned let container = container
        
        container.register(.weakSingleton) { RootPresenter() }
            .implements(AnyObject.self,
                        RootModuleInput.self,
                        AppDelegateOutput.self,
                        RootInteractorOutput.self)
            .resolvingProperties { container, presenter in
                presenter.delegate = UIApplication.shared.delegate as! AppDelegate
                presenter.router = try! container.resolve()
                presenter.interactor = try! container.resolve()
                presenter.deeplinkHandler = try! container.resolve()
                presenter.shortcutHandler = try! container.resolve()
        }
...

But in memory app has 5 instances of this class.
![screen shot 2017-05-19 at 11 28 35](https://cloud.githubusercontent.com/assets/9320927/26240180/c6d17cb0-3c88-11e7-86a8-13f5abc51976.png)


Please provide any solution!
