### ISSUE TITLE
New Version is broken (resolve fails)

### ISSUE THREAD

**Issue by vCrespoP** [AliSoftware/Dip#16]
Hi, I've upgraded from Dip 2.0.0 to Dip 3.0.0 (CocoaPods) and my code stopped working, just changing this:
whatever.register(...)
to
whatever.register(tag: ...)

Everything remains the same, so something internal has changed that's preventing from resolving things. The problem comes, after registering some instance, with the appropriate tag, when trying to resolve, seems that it cannot find that instance back.

I insist, I've only updated the pod and added the "tag" label as now is a requirement, everything else remains the same and doesn't work.

Thanks!

**Comment by ilyapuchka** [comment]
HI, @vCrespoP. It will really help if you provide the code that makes registrations and resolution.

**Comment by vCrespoP** [comment]
I think it's got nothing special, but you're right, it'll help debugging:

*Enum defined*
```
enum ManagerPersistenceType: String {
    case Memory
    case Disk
    var tag: DependencyContainer.Tag {
        return DependencyContainer.Tag.String(self.rawValue)
    }
}
```

*Both following code is called inside*
```
let dependencies: DependencyContainer

init() {
        
    dependencies = DependencyContainer {
        // Code Working in x.0.0
   }

}
```
*Working in 2.0.0*
```
let realmMemory = try! Realm(configuration: Realm.Configuration(inMemoryIdentifier: "MyInMemoryRealm"))
$0.register(ManagerPersistenceType.Memory.tag, instance: realmMemory)
            
let realmDisk = try! Realm()
            
if let realmPath = Realm.Configuration.defaultConfiguration.path {
     DDLogDebug("Realm Path: \(realmPath)")
}

$0.register(ManagerPersistenceType.Disk.tag, instance: realmDisk)
```

*Not working in 3.0.0 (Same but adding just "tag:" in register method) *
```
let realmMemory = try! Realm(configuration: Realm.Configuration(inMemoryIdentifier: "MyInMemoryRealm"))
$0.register(tag: ManagerPersistenceType.Memory.tag, instance: realmMemory)
            
let realmDisk = try! Realm()
if let realmPath = Realm.Configuration.defaultConfiguration.path {
    DDLogDebug("Realm Path: \(realmPath)")
}
$0.register(tag: ManagerPersistenceType.Disk.tag, instance: realmDisk)
```

Both are called like this:
```
func managerPersistenceForType(persistenceType: ManagerPersistenceType) -> Realm {
        let persistence: Realm = dependencies.resolve(persistenceType.tag)
        return persistence
}
```

I've made again the test => Upgrade to 3.0.0 and it's not working. Downgrade to 2.0.0 and works again :S

**Comment by ilyapuchka** [comment]
My guess is that probably you forgot to add `tag` argument in you `resolve` call. This way it will be treated not like a tag, but like a first runtime argument for factory, but such factory is not registered.

@AliSoftware, probably it would be better to make first runtime argument also named, so that it will look like `resolve(withArguments: arg1, arg2, ...)` ?

**Comment by vCrespoP** [comment]
Jackpot @ilyapuchka 

+1 to the naming convention you said. Feel free to close this issue or reuse it for this change. 

Thanks.

**Comment by ilyapuchka** [comment]
Glad to help. Sorry for such breaking changes in API =) I will create another issue for `withArguments` parameter name and we will probably release it pretty soon. For now I will add a migration note in Changelog.

**Comment by AliSoftware** [comment]
I'll all in for naming the first of the runtime arguments :+1: 

Not sure how it should be named though, `withArguments:` seems fine, but I'm also wondering if such a name couldn't let the user think that it expects an _array_ of arguments (like `resolve(withArguments:[arg1,arg2,arg3])`) here (but I couldn't find a better name either, but if you have ideas…)
