### ISSUE TITLE
Question on resolving with Tags

### ISSUE THREAD

**Issue by vander2675** [AliSoftware/Dip#165]
Hey, first of all: It's a really great Framework you provide. Thank you very much for it!

And to the question:
Is the  handing through of the tag only possible when using AutoWiring ? 
Or is it also possible when using registration like this:
```Swift
            container.register(.unique) {
                try Load<Chapter, Party>(request: container.resolve(), insert: container.resolve(), save: container.resolve()) as Load<Chapter, Party>
            }
```
Or do I have to register it this way?

```Swift
            container.register(.unique) {
                try Load<Chapter, Party>(request: $0 as GenericApiRequest<Party>, insert: $1 as BatchInsert<Chapter, Party>, save: $3 as Save)
            }
```

Second question:

Is registering with :
```Swift
            container.register(.unique, type: Load<Media, Chapter>.self, tag: nil, factory: Load<Media, Chapter>.init)
```
Using AutoWiring?

Thanks very much in advance.

**Comment by ilyapuchka** [comment]
You can get a tag from context object https://github.com/AliSoftware/Dip/wiki/Dependency-container-context, thats what autowiring does under the hood.

**Comment by vander2675** [comment]
Thanks for the quick response. Is Autowiring Constraint to an maximum number of Constructor dependencies?

**Comment by ilyapuchka** [comment]
yes, the constraint is not on autowiring, it is on registration methods (you can add your own but it is not advised)

**Comment by vander2675** [comment]
Ah I see. This was my problem. I will refactor my architecture here. Thank you!

**Comment by ilyapuchka** [comment]
Regarding you second question - autowiring is a feature to resolve dependencies of constructor without resolving them explicitly in registered factory or manually and passing as parameters to `resolve` method. So if you resolve this type with `resolve` it will use autowiring. More on that in docs in wiki.
