### ISSUE TITLE
Singleton not honored when collaborating containers

### ISSUE THREAD

**Issue by jtwigg** [AliSoftware/Dip#167]
Help! I've found what I believe to be a nasty bug with Collaborating containers and singleton registrations.

If I have a registration of ServiceA in a rootContainer as a singleton registration and I 
a) Resolve the ServiceA from the rootContainer
b) Make a child container the collaborates with the rootContainer
c) resolve ServiceA for a second time with rootContainer

The second resolve of ServiceA is a new instance. I think the call to collaborate with rootContainer wipes the registry clean!

```
  class ServiceA {}

  func testSingletonNotHonored() {
    var count = 0

    let rootContainer = DependencyContainer()
    rootContainer.register(.singleton) { () -> ServiceA in
      count = count + 1
      return ServiceA()
    }

    let s1:  ServiceA = try! rootContainer.resolve()//<<<< Aquire the service

    let childContainer = DependencyContainer()

    childContainer.collaborate(with: rootContainer) // <<< Collaborate with root service

    //NOTE: I believe the root service is now broken. Its forgotten about its
    //singleton registration of ServiceA

    let s2:  ServiceA = try! rootContainer.resolve()

    XCTAssert(s1 === s2) //<<<<<< FAils
    XCTAssert(count == 1) //<<<<< FAILS
  }

```

NOTE: If you resolve the ServiceA twice After the collaboration, the singleton is honored.

This is important to our team because we want to make modules that are isolated from each other, but have access to root container singletons and this is the only approach that can do this.

I even modified your  [Collaboration Wiki](https://gist.github.com/jtwigg/5a148bfd358169e585f873d5cdefdbc2) example to show that the DataStore singleton can be broken.

**Comment by jtwigg** [comment]
Digging through the collaboration code, I'm worried that this whole approach is never going to work.
Whenever anyone collaborates with another container, it 
a) overrides all its resolved instances in ...
```
public func collaborate(with containers: [DependencyContainer]) {
```
(which is almost certainly the bug I'm seeing)

b) It then recurses into the collborators->collaborators and over rights its dependancies too. It forces them to use the same 'singletonsBox'. This is a sort of coerced collaboration.

An example of this is in your wiki example
https://github.com/AliSoftware/Dip/wiki/containers-collaboration

The following collaboration match up
```
eventsListModule.collaborate(with: addEventModule, rootContainer)
addEventModule.collaborate(with: eventsListModule, rootContainer)
```
 can be replaced with
```
eventsListModule.collaborate(with: rootContainer)
addEventModule.collaborate(with: rootContainer)
```
and now eventsListModule &  addEventModule are coerced into collaborating with each other.

I would expect the test to fail, but it passes.

**Comment by ilyapuchka** [comment]
You should first setup your containers and only then resolve.

**Comment by jtwigg** [comment]
@ilyapuchka Thanks for the prompt response. 
Lets say that setting up the containers initially is a requirement. So be it. I believe I still have a problem

What I'm trying to do is create isolation between two independent containers who share a common root container with signletons. Example: logged in container, unlogged in container. 

This is in the vain of [Guice Private modules](https://google.github.io/guice/api-docs/latest/javadoc/index.html?com/google/inject/PrivateModule.html) or [Dagger 2 Subcomponents / Componennts (don't know which one)](https://stackoverflow.com/questions/29587130/dagger-2-subcomponents-vs-component-dependencies)

I find I can either get it into one of two states
a) Common Roots singletons work, but containers are not isolated 
b) Common root singletons fail, but containers are isolated.


```
 
  class ServiceA {}

  class Password {
    let text: String
    let service : ServiceA

    init(text:String, service: ServiceA) {
      self.text = text
      self.service = service
    }
  }


  func test_IsolationWorks_RootSingletonFails() {

    let rootContainer = DependencyContainer()

    var count = 0
    rootContainer.register(.singleton) { () -> ServiceA in
      count = count + 1
      return ServiceA()
    }

    let loggedIn = DependencyContainer()
    loggedIn.register(.singleton) { Password(text: "1234", service:$0) }

    let unloggedIn = DependencyContainer()
    unloggedIn.register(.singleton) { Password(text: "-none-", service:$0) }

    loggedIn.collaborate(with: rootContainer) //Isolated containers
    unloggedIn.collaborate(with: rootContainer)//Isolated Container


    let passwordA = try! unloggedIn.resolve() as Password
    let passwordAv2 = try! unloggedIn.resolve() as Password

    XCTAssert(passwordA.text == "-none-") //<< Works
    XCTAssert(passwordAv2.text == "-none-")//<< Works
    XCTAssert(count == 1) ////<< Works

    let passwordB = try! loggedIn.resolve() as Password
    XCTAssert(passwordB.text == "1234") //<<<works
    XCTAssert(count == 1) //<<< !!!!FAILS!!!
    
  }



  func test_SingletonWorks_IsolationPasswordFails() {

    let rootContainer = DependencyContainer()

    var count = 0
    rootContainer.register(.singleton) { () -> ServiceA in
      count = count + 1
      return ServiceA()
    }

    let loggedIn = DependencyContainer()
    loggedIn.register(.singleton) { Password(text: "1234", service:$0) }

    let unloggedIn = DependencyContainer()
    unloggedIn.register(.singleton) { Password(text: "-none-", service:$0) }

    loggedIn.collaborate(with: rootContainer, unloggedIn) //Cross collaborate
    unloggedIn.collaborate(with: rootContainer, loggedIn) //Cross collaborate


    let passwordA = try! unloggedIn.resolve() as Password
    let passwordAv2 = try! unloggedIn.resolve() as Password

    XCTAssert(passwordA.text == "-none-") //<< !!!FAILS!!
    XCTAssert(passwordAv2.text == "-none-")//<< !!FAILS!!
    XCTAssert(count == 1) ////<< Works

    let passwordB = try! loggedIn.resolve() as Password
    XCTAssert(passwordB.text == "1234") //<<<WORKS
    XCTAssert(count == 1) //<<<Works
    
  }

```


The only variant that works is where I go straight to rootContainer to resolve serviceA
```
unloggedIn.register(.singleton) { Password(text: "-none-", service:try rootContainer.resolve()) }
```
where I have to drag in a lot of implementation knowledge about where and how the serviceA got registered.

*Thoughts?*

**Comment by jtwigg** [comment]
So be it: 
I'm opening a question regarding child containers as a result.
