### ISSUE TITLE
Is it possible to inject generics? 

### ISSUE THREAD

**Issue by nikans** [AliSoftware/Dip#175]
Take for example `Service` as a protocol with some `assiciatedtype`s and `ServiceImp1: Service` and `ServiceImp2: Service` generic classes. 
I haven't tested yet, but a mind exercise tells me that it shouldn't work. Am I right?

**Comment by ilyapuchka** [comment]
You can't do `register { ServiceImp1() as Service }`, it's a Swift limitation, not Dip. You can do `register { ServiceImp1() }` but it will only register concrete type. You can try to apply type-arasure technique if it suites your case.
