### ISSUE TITLE
New release for collaboration crash?

### ISSUE THREAD

**Issue by kaosdg** [AliSoftware/Dip#181]
I'm experiencing a crash with collaborating containers (resolve returns the wrong type) and noticed that it's fixed in develop with this commit:  https://github.com/AliSoftware/Dip/commit/9e7bd51bcd86363638c29a777934e2188f021543#diff-fbe062135860a10a57ff5a8d49acec3b

Any chance to get this into a 6.0.1 release?

**Comment by kaosdg** [comment]
@ilyapuchka any word on this?

**Comment by mylemans** [comment]
wondering the same here

**Comment by ilyapuchka** [comment]
Release is done (#190)
