### ISSUE TITLE
Resolving dependencies for UIViewControllers at runtime without using DipUI

### ISSUE THREAD

**Issue by ascendedco** [AliSoftware/Dip#187]
When using StoryBoards to instantiate UIViewControllers, resolving dependencies is very straight forward. Currently, I do it as follows: 

```swift
container.register(storyboardType: MessagesController.self, tag: nil)
            .resolvingProperties { container, controller in
                controller.presenter = MessagesPresenter(
                    view: controller,
                    mapper: ViewMessageMapper(),
                    messageRepository: try container.resolve() as MessageRepository,
                    userRepository: try container.resolve() as UserRepository
                )
            }
```

How would I accomplish this for a UIViewController that is created using init() and not instantiated by a StoryBoard? I really need this since some of the UIViewControllers in my project are created completely in code and have no StoryBoard files. I thought of getting a reference to container in the controller, but that would just be creating the ServiceLocator anti-pattern.

This is how these controllers are typically created in response to user actions: 

```swift
let chat = ChatController()
chat.chat = chats[indexPath.row]
navigationController?.pushViewController(chat, animated: true)
```

**Comment by ilyapuchka** [comment]
If you are creating controller in code you can pass all dependencies in `init` and use auto-wiring. If you still want to use `init()` you'll have to make your properties mutable to be able to inject them manually in `resolvingProperties`, or use auto-injection.

**Comment by ilyapuchka** [comment]
The only thing that DipUI does is that it registers "dummy" factory which will never be called (unless controller is resolved manually and not created from storyboard) and calls `resolve` as soon as controller is instantiated from storyboard. When you create controllers in code it's no different from resolving any other kind of types.

**Comment by ascendedco** [comment]
Sorry, I still don't understand how that would work, since `ChatController` is not instantiated in the composition root. Could you perhaps provide a short example?

**Comment by ilyapuchka** [comment]
You don't have to instantiate view controllers in composition root. You can create a factory that will create this controller when you ask it. Container can play as such factory if you use it through some factory interface, not with `resolve`:

**Comment by ascendedco** [comment]
Okay, I think using what you described here would be best: 

> if you still want to use init() you'll have to make your properties mutable to be able to inject them manually in resolvingProperties

The only question I have then is how should ChatController be registered to enable `resolvingProperties` to be called?

**Comment by ilyapuchka** [comment]
The same way as any other type.

```
container.register(ChatViewController.init).resolvingProperties { ... }
```

**Comment by ascendedco** [comment]
Thank you, I didn't see that registration use case in the docs. Are you accepting PR's for documentation? I think it would be useful to have some Clean Architecture use cases shown with DIP.

**Comment by ascendedco** [comment]
Getting the following compiler error: 

Ambiguous reference to member 'init(nibName:bundle:)'

**Comment by ilyapuchka** [comment]
I think wiki contains excessive docs and enough examples, please check it.

**Comment by ascendedco** [comment]
Thanks, managed to convert ChatController so it's instantiated by StoryBoard. Couldn't get it to resolve properly otherwise.
