### ISSUE TITLE
Xcode 10 / Swift 4.2 does not work

### ISSUE THREAD

**Issue by SlashDevSlashGnoll** [AliSoftware/Dip#200]
We're trying to update our app to the latest SDK and discovered that Dip no longer builds or functions with the latest language changes.

`ImplicitlyUnwrappedOptional` is no longer a type.  We tried removing this extension on `BoxType` which gets it to build but it crashes at runtime.  Is anyone working on updating this currently?

**Comment by ilyapuchka** [comment]
Please use `swift42` branch. Swift 4.2 is not released yet, so this is not in master.

**Comment by SlashDevSlashGnoll** [comment]
Sorry about that, I could swear we looked for one but apparently not.
