### ISSUE TITLE
xcode 10 support

### ISSUE THREAD

**Issue by ildarsharafutdinov** [AliSoftware/Dip#205]
Since Xcode 10 fails to compile the latest 6.1 there is definitely a need for a new version.

Are there plans to release `swift42` branch?

**Comment by zunjae** [comment]
Also fails for me with the error "Header 'Dip-Swift.h' not found"

Is my only option to downgrade XCode?

**Comment by Gruppio** [comment]
@zunjae are you using the swift42 branch ?

**Comment by zunjae** [comment]
No I am not because I have no idea how, though I've manually updated the source code for Dip in order to make it work in my application.

**Comment by hellbit** [comment]
I have 2 errors. Use swift 4.0
1. 'ImplicitlyUnwrappedOptional' has been renamed to 'Optional'
2. Command CompileSwift failed with a nonzero exit code

**Comment by vinters768** [comment]
@zunjae   pod 'Dip', :git => 'https://github.com/AliSoftware/Dip.git', :branch => 'swift42'

**Comment by AndrewKochulab** [comment]
Where is the branch swift 42?
This library still crashes on the Xcode 10.

**Comment by vinters768** [comment]
> Where is the branch swift 42?
> This library still crashes on the Xcode 10.

try using this in your Podfile: 
pod 'Dip', :git => 'https://github.com/AliSoftware/Dip.git', :branch => 'swift42'

**Comment by AndrewKochulab** [comment]
> > Where is the branch swift 42?
> > This library still crashes on the Xcode 10.
> 
> try using this in your Podfile:
> pod 'Dip', :git => 'https://github.com/AliSoftware/Dip.git', :branch => 'swift42'

There is no branch with name swift42
Errors from the terminal:
[!] Error installing Dip
[!] Failed to download 'Dip'.

**Comment by vinters768** [comment]
> > > Where is the branch swift 42?
> > > This library still crashes on the Xcode 10.
> > 
> > 
> > try using this in your Podfile:
> > pod 'Dip', :git => 'https://github.com/AliSoftware/Dip.git', :branch => 'swift42'
> 
> There is no branch with name swift42
> Errors from the terminal:
> [!] Error installing Dip
> [!] Failed to download 'Dip'.

it looks like @ilyapuchka updated master for Swift 4.2 support, if you're still having issues, try removing and re-adding Dip from the Podfile, or try an empty project.. it works fine for me.
