### ISSUE TITLE
Dip 7.0.0 not working with Swift Package Manager

### ISSUE THREAD

**Issue by fedal-mas** [AliSoftware/Dip#213]
I've update my project to swift 4.2, but when I try to update Dip to 7.0.0, it doesn't work. Even if I clone the repo and add it as a dependency using the local path, I always end up with this problem: 

``` shell
error: terminated(128): git -C /Users/.../.build/checkouts/Dip.git-3060003739911156547 checkout -f 593129c63ec840144208827363c7d13e8c867c30 output:
    


```

Any thoughts? I'm really stuck on this.

**Comment by fedal-mas** [comment]
@ilyapuchka I think that the problem might be that the 7.0.0 version is not compatible with the swift package manager. Any other version is added without any problem, but doesn't work because it is an old swift version 😑

**Comment by ilyapuchka** [comment]
I'm not sure what this incompatibility might be. Can you post your complete `Package.swift` file?

**Comment by fedal-mas** [comment]
Actually now it's working! 

Really don't know why, I haven't made any changes on my `Package.swift` file, except by commenting and uncommenting the line to add Dip... 🤔

Anyway, thanks for your time!
