### ISSUE TITLE
Question: How to resolve all instances implementing a common protocol?

### ISSUE THREAD

**Issue by mylemans** [AliSoftware/Dip#215]
At the moment, in a separate step, we resolve a specific set of protocols so they can perform additional configuration steps.

In the past when I developed on Windows I would just give all these services a common interface (protocol) that they would have to implement, and then I just had to get all instances implementing that interface. How would I go on reproducing such behaviour using Dip?

**Comment by ilyapuchka** [comment]
@mylemans in early days there was an idea to support [multi-injection](https://github.com/AliSoftware/Dip/issues/14) but we dropped it as the same result can be achieved with tags and `map` function (see https://github.com/AliSoftware/Dip/pull/39#issuecomment-177610238)
