### ISSUE TITLE
Inject properties in storyboard root view controller

### ISSUE THREAD

**Issue by alphatroya** [AliSoftware/Dip#218]
It looks like storyboard support not work well when I specify `Main Interface` parameter in project settings (without manual configuration it in the AppDelegate). Does Dip support this case?

**Comment by ilyapuchka** [comment]
Have you checked the sample app? It uses this setting and works as expected.

**Comment by alphatroya** [comment]
The sample app performs all needed setup in AppDelegate method, but I think about a more "automatic" approach. `Swinject` have a [SwinjectStoryboard](https://github.com/Swinject/SwinjectStoryboard#implicit-instantiation-from-main-storyboard) class for implicit creation root controller without any code in AppDelegate method. Do you think about a similar solution?

**Comment by ilyapuchka** [comment]
@alphatroya yes, and I don't think it brings enough value to justify method swizzling. The framework shouldn't be that much intrusive.

**Comment by alphatroya** [comment]
Yes, maybe you're right. Close this issue.
