### ISSUE TITLE
Warnings resolve?

### ISSUE THREAD

**Issue by tereks** [AliSoftware/Dip#228]
Hi, any chance these two warning will be resolved?
'Hashable.hashValue' is deprecated as a protocol requirement; conform type 'DefinitionKey' to 'Hashable' by implementing 'hash(into:)' instead
Coercion of implicitly unwrappable value of type 'DependencyContainer.Context?' to 'Any' does not unwrap optional

**Comment by ilyapuchka** [comment]
resolved with 7.1.0
