### ISSUE TITLE
Update master branch

### ISSUE THREAD

**Issue by Gruppio** [AliSoftware/Dip#230]
Hi,

The master branch is left behind and is missing a lot of useful stuff that is available in develop like a valid Package.swift file and the porting to swift 5

Do you think that is develop mature enough to be merged in master and release a new version in cocoapods?

Many thanks for your work! :-) 

Gruppio

**Comment by ilyapuchka** [comment]
Can't push update because cocoapods trunk has issues with custom email domains, so if you want this now use master when #231 is merged
