### ISSUE TITLE
Use of undeclared type 'StoryboardInstantiatable' on SPM installation

### ISSUE THREAD

**Issue by alphatroya** [AliSoftware/Dip#232]
I move from Carthage to SPM installation after 7.1.0 release but encounter with the issue of my project compilation. Other methods and classes resolving fine. 

Update to the latest version by Carthage is also working fine.

**Comment by ilyapuchka** [comment]
I guess it's expected as AFAIK it's still not possible to use SPM to manage dependencies of the iOS apps, or ha a storyboard as a SPM framework resource. So we have this type stripped away with `#if !SWIFT_PACKAGE`

**Comment by alphatroya** [comment]
Well, not sure that I correctly understand you, but XCode 11 is out with full SPM support (including iOS). I've already switched many of my project dependencies from Carthage. Many of that dependencies is iOS only framework.

**Comment by ilyapuchka** [comment]
I'm just curious how do you link SPM dependencies to iOS application targets

**Comment by alphatroya** [comment]
I use "Swift Packages" tab in the project settings

<img width="1512" alt="Снимок экрана 2019-11-13 в 12 28 50" src="https://user-images.githubusercontent.com/4927633/68750672-4af4f680-0611-11ea-9f78-ca6f80cb65ea.png">
<img width="1512" alt="Снимок экрана 2019-11-13 в 12 29 00" src="https://user-images.githubusercontent.com/4927633/68750674-4af4f680-0611-11ea-853e-707eeacd66de.png">
<img width="1512" alt="Снимок экрана 2019-11-13 в 12 29 11" src="https://user-images.githubusercontent.com/4927633/68750675-4af4f680-0611-11ea-90b6-0c52d494a0d7.png">

**Comment by ilyapuchka** [comment]
Nice, never used this yet 👍
