### ISSUE TITLE
Making container final

### ISSUE THREAD

**Issue by ilyapuchka** [AliSoftware/Dip#24]
Should we make `DependencyContainer` class `final`? I don't think there are any use cases for subclassing it. If clients want to extend behavior of container they can use composition. Also we never thought about supporting inheritance (maybe some properties should be not internal/private for that) so it can be just safer for clients to [make it final](https://github.com/jspahrsummers/library-oriented-programming/blob/master/Library-Oriented%20Programming.md#fit-final).

**Comment by AliSoftware** [comment]
:ok_hand:

http://youtu.be/ZXsQAXx_ao0

**Comment by ilyapuchka** [comment]
Resolved by 6ad4b82ec0a8969b8be80a407bc9a306ef4ff33c
