### ISSUE TITLE
What is Arg?

### ISSUE THREAD

**Issue by onmyway133** [AliSoftware/Dip#27]
Hi, I'm trying Dip. One thing that I wonder is what `Arg` is, as in

```
public func resolve<T, Arg1>(tag tag: Tag? = nil, withArguments arg1: Arg1) throws -> T {
    return try resolve(tag: tag) { (factory: (Arg1) -> T) in factory(arg1) }
  }
```

I can't seem to find where `Arg1` is defined

**Comment by AliSoftware** [comment]
It's a [generic type](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Generics.html) (as defined inside the angle brackets), exactly like the type `T`; so it can be anything you want!

**Comment by onmyway133** [comment]
@AliSoftware: Thanks for your very fast response. I just realized that.
