### ISSUE TITLE
Storyboards support

### ISSUE THREAD

**Issue by ilyapuchka** [AliSoftware/Dip#34]
With auto-injection merged everything will be ready to support auto-injection in objects created by storyboards. I think it will be nice to release those features together. Actually I already have it implemented in my fork and already tried it in a simple project. @AliSoftware you can check it out in [this brunch](https://github.com/ilyapuchka/Dip/tree/feature/storyboards). 

We discussed that we can use separate repository for that feature, like Dip Extensions. The thing is that it is not that much, I think now, that we can put there and maybe it will be not efficient. But on the other side we will need to create separate targets for each platform anyway if we want to keep core of Dip independent from UIKit, whether for CocoaPods or carthage, right?

**Comment by AliSoftware** [comment]
I still prefer a separate repo at least for now.

I'm not sure how much there will be to put in there actually. So maybe I'm thinking it will be bigger than it will actually be. But given the various targets needed to add I still don't want to clobber the core.

**Comment by ilyapuchka** [comment]
Ok, can you maybe create it then? I think it will make sense to keep it in your name space too.

**Comment by AliSoftware** [comment]
I was thinking to call it `Dip-UI`, have a better suggestion?

**Comment by ilyapuchka** [comment]
There could be features not directly connected with UI. Maybe just Dip-Extensions, or Dip-Utils?

**Comment by ilyapuchka** [comment]
But I like the compactness of Dip-UI :smile:

**Comment by AliSoftware** [comment]
Let's use https://github.com/AliSoftware/Dip-UI for now and rename later if needs be.

I made it empty, and let you create the README, CHANGELOG, .gitignore and stuff to fit.

**Comment by ilyapuchka** [comment]
Support for storyboards is implemented in https://github.com/AliSoftware/Dip-UI/pull/1
