### ISSUE TITLE
Support watchOS2, tvOS, OSX?

### ISSUE THREAD

**Issue by AliSoftware** [AliSoftware/Dip#4]
I don't think anything should prevent `Dip` from working on those other platforms, but I'll have to check first by creating some example before adding that support in the `podspec`.

**Comment by AliSoftware** [comment]
_BTW, To anyone that would have the occasion to try it out on those platforms, i'm interested in your feedback (and dont hesitate to make a PR in such case!)_

**Comment by ilyapuchka** [comment]
I suppose to support use of Carthage (not sure how it works in CocoaPods) for other platform we need first of all to create corresponding framework targets for those platforms. I would suggest to do it with 4.0.0 release. To prove that frameworks work correctly I think it would be enough to use the same tests as we use now for all of the platforms. I don't think there is any specific functionality now that can be broken on any of those platforms. Later (after integrating in iOS app) I will probably use Dip also in watchOS app for my new project and in tvOS app if there will be any. But that's a plan for a next year only.

**Comment by AliSoftware** [comment]
Yeah as long as we don't use UIKit (yet) in Dip I don't think there will be any problem but better safe than sorry, but current unit tests should do the trick.

When we add UIKit support to Dip that will be another story, but that's also a reason why I want those UIKit extensions in a separate lib.

For CocoaPods all there is to do is add a line in the podspec. That's all.

For Carthage sadly that requires duplication the target building the framework. Which is not the best for maintenance because we would have to duplicate the Build Settings for each and don't forget to update then everywhere if we were to change one of them. Maintaining Carthage is usually more work for lib authors for this reason and also because you have to do some manual process like fmk upload each time you create a new release

**Comment by ilyapuchka** [comment]
Yes, Carthage is simpler but requires more work and head ace some time. Regarding uploading binaries for new releases isn't that discouraged cause there is still no ABI stability? They promise it in [Swift 3.0 only](http://ericasadun.com/category/swift/) and that would happen next autumn. And anyway in my experience there were more problems with that then advantages. Actually in near future I plan to try to use Carthage just to checkout source code, not even build frameworks.

**Comment by AliSoftware** [comment]
No the ABI compatibility is not a problem here.
The fact that you link with a framework that was built with Swift 2 ABI or that you recompile from the sources which will produce a Swift 2 ABI binary leads to the same.
That will only cause an issue when Swift 3 goes out and your app code will be using the Swift 3.0 ABI but the pre-built framework would still be with Seift 2 ABI, but (1) we have time before it arrives and (2) the Swift 2 source code probably won't compile with Swift 3 right away and need minor modifications anyway so building from sources won't work anymore without those changes when that time comes.

When you link with a framework containing Swift, Xcode copies the Swift Runtime dylibs into the app bundle (using the swift-stdlib-tool) so that it doesn't depend on the Swift ABI bundled in iOS but the one in your app bundle and you app is a bit bigger but at least will comtinue working even when iOS 10 comes out and will be shipped with Swift 3 runtime and ABI. So that isn't an issue either,

Carthage recommend uploading the prebuilt framework as a binary attachment to your GitHub releases anyway. You're not required to do it but if you don't do it it will rebuild the code from source during `carthage install` and people often complain and open issues asking for those prebuilt frameworks anyway.

**Comment by ilyapuchka** [comment]
Have an issue with watchOS2 framework target. There is no "Enable Bitcode" setting for such target, but Carthage requires it to be set to YES. I didn't work with watchOS2 so probably I'm doing something wrong. @AliSoftware can you please take a look? I pushed it here 42f0945ebef23f1456a7ef93532fa84e99e1e05f

**Comment by AliSoftware** [comment]
Mmhh that's probably a Carthage issue.

WatchOS2 targets are _always_ using BitCode, that was a requirement from the start when watchOS2 was released so there is no way to turn it off, hence the absence of such setting in watchOS2 targets' Build Settings in Xcode.

So Carthage shouldn't check for those in such case (are you using the latest release of Caryhage from the PKG installer? The formula in Homebrew for Carthage doesn't work anymore)

You may try to add it as a User-Defined build setting in the watchOS target to fool Carthage, but that's probably worth filing an issue to the Carthage repo if not already existing.

**Comment by ilyapuchka** [comment]
It's strange then that in WatchApp there is still Enable Bitcode setting =) Problem was that I didn't have any simulator paired with watch simulator.

Regarding Carthage, do they really _recommend_ to upload binary builds? Can you share any link?

**Comment by AliSoftware** [comment]
Sure, [here it is](https://github.com/Carthage/Carthage/blob/master/README.md#archive-prebuilt-frameworks-into-one-zip-file)

**Comment by ilyapuchka** [comment]
Yep, I just thought that they explicitly encourage to use this feature. The thing is that I had some hard time making it work when I had a bunch of frameworks with several levels of dependencies. Hope that will be not a case for Dip =) Then will make a PR for this issue.
