### ISSUE TITLE
Resolve singleton to multiply interfaces?

### ISSUE THREAD

**Issue by Koshub** [AliSoftware/Dip#47]
Is it possible to use singleton to resolve different interfaces
```swift
class ServiceImp {}
extension ServiceImp : SomeService {}
extension ServiceImp : AnotherService {}

let container = ...
container.register(.Singleton) { ServiceImp() as SomeService }
container.register(.Singleton) { ServiceImp() as AnotherService }
```
Probably we could use next:
```swift
let service = ServiceImp()
container.register(.Singleton) { service as SomeService }
container.register(.Singleton) { service as AnotherService }
```
But does it makes sense?

**Comment by ilyapuchka** [comment]
Yes, such setup makes sense. In this case you don't even need to specify Singleton scope - you will also get the instance you have created manually resolving both types.

The other thing is that if you have such situation you probably violate Single Responsibility Principle (even if you break your code using extensions it's still the same type implementing different behaviors). It is up to you to decide if it is ok for your particular case, or something you may wish to change.

**Comment by Koshub** [comment]
@ilyapuchka . You are right. But the reason is there is no more accurate method to implement it than next one:
```swift
let container = ..
container.register(. Singleton) { ServiceImp() as ServiceImp }
container.register() { c in  (c.resolve() as ServiceImp) as SomeService }
container.register() { c in (c.resolve() as ServiceImp) as AnotherService }
```
My question is not about Single Responsibility Principle, it is about API

**Comment by ilyapuchka** [comment]
This will also work. As for me it's not that clean as the first solution that you proposed, but it makes creation of singleton instance lazy.
Just few notes: you don't need `as` in the first definition and you don't need `c` argument in the factories of two other definitions, you can use `container` in the factories.

Is there anything else?

**Comment by ilyapuchka** [comment]
@Koshub btw type forwarding will help in this case. With it you can do the following:

```swift
let service = container.register(.Singleton) { ServiceImp() as SomeService }
container.register(service, type: AnotherService.self)
```
Then you will be able to resolve both types using the same definition and reuse instance if it's registered in Singleton or ObjectGraph scope.

The downside of that is that there is no way to ensure type safety, meaning that to ensure at compile time that instance created by the factory also implements forwarded type (AnotherService in this example)

**Comment by Koshub** [comment]
@ilyapuchka Thank you. Will try

**Comment by rupenrana** [comment]
Is there any way to set my class singleton using Dip? I mean componentScope.singleton is doing this for us but in code my class is ordinary looking class with no private init(). Is there any way that no body can make another instance of it in code?

**Comment by ilyapuchka** [comment]
Hi @rupenrana . No, dependency containers do not apply any constraints on your objects, they only control their lifecycle. But no one is stopping you from making your class a singleton and register it in container. Scope will not matter in this case, obviously.

**Comment by rupenrana** [comment]
@ilyapuchka thanx for your answer, So how its possible? I mean if I make my class singleton with private init. How to register it with container with no public init?

**Comment by ilyapuchka** [comment]
You still have a public accessor to the shared instance, so you just use it in registered factory:

```swift
container.register { MySingleton.shared as MySingletonProtocol }
```

**Comment by rupenrana** [comment]
@ilyapuchka Here comes the problem, now by doing this there is no way that we can set dependency on the singleton class by constructor dependency. Correct me if I am wrong?

**Comment by ilyapuchka** [comment]
Obviously, but that comes with a fact that you want to have a singleton in a first place, it has nothing to do with container. You can still use property injection, it will be implemented only once . The only way you can workaround that is to define `fileprivate` constructor on a singleton type with its dependencies as arguments and in the same file put a function that will register definition with this constructor. This will obviously couple your code with container which I usually do not recommend.
