### ISSUE TITLE
Organise documentation

### ISSUE THREAD

**Issue by ilyapuchka** [AliSoftware/Dip#52]
I think it would be better to make README shorter, demonstrating only basic usage of Dip and list of available features, moving their description to separate md files (or wiki pages?)

**Comment by AliSoftware** [comment]
:+1:
That's what I did on [OHHTTPStubs](https://github.com/AliSoftware/OHHTTPStubs), moving away all the usage examples in a dedicated wiki page as the README was starting to get too big.

You can inspire you from the same idea.

---

Just be sure the pod doesn't lower its README score too much on CocoaPods (see [Dip's quality index page here](https://cocoapods.org/pods/Dip/quality))

[CocoaPods's quality index is explained here](https://guides.cocoapods.org/making/quality-indexes) but long story short, to have those extra points and be considered a "great README" is is expected to have a score > 75 on http://scoreme.report/ (we're at 100 right now so I we're really :+1: on that front :simple_smile: but reducing the file too much lower it)
