### ISSUE TITLE
Resolvable.didResolveDependencies() called in the wrong order

### ISSUE THREAD

**Issue by sebastian-zarzycki-es** [AliSoftware/Dip#66]
I have a MyViewController that is StoryboardInstantiatable and Resolvable. It's initialized via:

`storyboard.instantiateViewControllerWithIdentifier("myController") as! MyViewController`

it has a MyViewModel dependency, resolved as such:

```
container.register(tag: "MyView") { MyViewController() }.resolveDependencies { container, entity in
  entity.myViewModel = try! container.resolve() as MyViewModel
}
```
MyViewModel is also registered in container and also has some dependencies.

The problem is that the order of calling didResolveDependencies() is wrong. When the MyViewController is instantiated, its dependencies are resolved, so MyViewModel is resolved. I would expect, that MyViewModel.didResolveDependencies() would be called first, as it is at that time, when this object is created and configured. Instead, MyViewController.didResolveDependencies() is called first, and MyViewModel.didResolveDependencies() is called later, which leads to null pointer errors, because controller assumes that ViewModel is entirely ready to work. But at that point, it's not ready because the starting operations defined in its own didResolveDependencies() weren't executed yet.

**Comment by ilyapuchka** [comment]
I've made a fix. Note though that `didResolveDependencies` will be called after the whole dependency graph is created, for each newly created instances, now with this fix, in order of stack (last created - first called). We could call them one by one before returning instance from `resolve` but that can also lead to null pointers (because returned instance is not yet assigned to any property). 

```swift
container.register(tag: "MyView") { MyViewController() }.resolveDependencies { container, entity in
  entity.myViewModel = try! container.resolve() as MyViewModel
  //didResolveDependencies is not yet called on model at this point
}

let vc = try! container.resolve(tag: "MyView") as MyViewController
//model.didResolveDependencies called
//vc.didResolveDependencies called
```

**Comment by sebastian-zarzycki-es** [comment]
Fully understood. Yes, that's probably the best way to do it and I accept this minor drawback. Most of the time it shouldn't really matter. Thanks for quick reaction, Ilya! This is much appreciated, we're actually using this on a production application and we have a release tomorrow :)

**Comment by sebastian-zarzycki-es** [comment]
Was that fix released in new Dip version are you going to release it later? Can't any Pod update so far.

**Comment by ilyapuchka** [comment]
I planned to release it later today. Can you use develop branch for now?

**Comment by sebastian-zarzycki-es** [comment]
If it's going to be released later today, I can wait, no problem. Thanks.
