### ISSUE TITLE
Dependency resolve timing

### ISSUE THREAD

**Issue by sebastian-zarzycki-es** [AliSoftware/Dip#68]
Not really an issue, more of a question, so apologies if that's not the right place. 

I'm not super familiar with inner Swift workings on a thread/execution level. I've been wondering how does Dip actually works in terms of timing of object creation. If I have an object that has a depedency and this depedency is configured in Dip, if I instantiate this object, are all its depedencies resolved and injected before the next line of code in that thread is executed, or does it happen sometime later?
```
let myObject = MyObject()
print(myObject.itsDepedency) // is it already injected and ready here?
```
Obviously, the depedency isn't injected on a initializer level (in MyObject init() method), but when does that happen exactly? Right after?

The reason I'm asking is that in other IoC architectures in other environments, such operation was never safe - you just couldn't assume that all depdencies are injected right away. And thus some callbacks were there just for that (the same thing as with Resolvable and didResolveDependencies I asked for before). However, I'm noticing that in Swift, somehow the dependencies are there right after object instantiation. Is it always like this and is supposed to be like this, or is it just a pure timing coincidence?

**Comment by ilyapuchka** [comment]
Resolution is performed right away in the current thread. Register/resolve methods are thread safe (recursive lock is used for that). When `let myObject = try! container.resolve() as MyObject` returns myObject is guarantied to have all configured dependencies injected. If something fails on the way exception is poped up. So it works the same way as if you were creating components manually. That's not going to change.

Resolvable callback in that sense serves more for separating components configuration and their usage, which I think is a good thing. And also it's the moment when all properties are guarantied to be injected (manually injected and auto-injected). The only thing that might change in future in terms of timing is that auto-injection can be performed before `resolveDependencies` block is called (now it's performed after). But no specific plans for that for now.

**Comment by sebastian-zarzycki-es** [comment]
Thank you, that's exactly what I wanted to know. I also agree with the Resolvable callback justification.
