### ISSUE TITLE
We could use a simpler Sample project

### ISSUE THREAD

**Issue by AliSoftware** [AliSoftware/Dip#7]
I feel like the current Sample Project grow a bit too much and went probably too far and complicated, because I wanted to make it closer to a real-world project but as a result the usage of `Dip` is probably not enough in the center of the Sample anymore.

We probably could have a simpler Sample project which would concentrate on `Dip` itself, be less complex and avoid any other complexities or wandering.

**Comment by ilyapuchka** [comment]
What about using playground to demonstrate use of all APIs? It will be easier than to come up with solid sample app that will make sense.

**Comment by AliSoftware** [comment]
:+1: seems like a tremendous idea! Would indeed be perfect!

Note that I started as a sample project because I wanted to demonstrate the usefulness of Dip and Dependency Injection for Unit Testing.

Using a playground wouldn't allow to demonstrate that in a concrete way, but I'm now more interested in having a comprehensive playground with simple API usage demos as you suggest (we could even make it multi-page and go from simple to advanced usage) than having a project just to demonstrate unit tests with Dip :wink:

**Comment by ilyapuchka** [comment]
We now have a playground https://github.com/AliSoftware/Dip/pull/10 =)

**Comment by AliSoftware** [comment]
Do you think we can close this issue now that we have a playground or do you think later in the future we should add a better sample app too (maybe one that leverage all the features — like Circular Dependencies and Runtime Arguments — in a real-world project?

**Comment by ilyapuchka** [comment]
I was thinking about to suggest to adopt [this project](https://github.com/ilyapuchka/ViewControllerThinning/tree/typhoon) to use Dip and include it or reference to it as an example. It already demonstrates how to use DI with Typhoon, so maybe it can be interesting to compare it with Dip. Also it's a part of my slowly going side project, so I was going to try Dip there anyway. 
But I can not guaranty how fast I will be able to do it so I think we can close this issue for now. Playground is much more illustrative and let's concentrate on Dip functionality without distracting.

**Comment by AliSoftware** [comment]
Perfect, fine by me (and no pressure I know how it is to have a lot of things ongoing and to lack time to do everything fast :wink:)
