### ISSUE TITLE
Is there a way to combine containers?

### ISSUE THREAD

**Issue by amccarri** [AliSoftware/Dip#91]
Similar to merge from Kotena or parent containers in Swinject?

**Comment by ilyapuchka** [comment]
Hi @amccarri 
There is no plan to introduce any kind of complex containers hierarchy features cause I simply don't see use cases that can not be solved with named definitions. Would be cool if you share your use case.
What I was thinking of is something very simple like collaborating containers that will be used if type is not registered in the container.

**Comment by fljot** [comment]
@ilyapuchka
>What I was thinking of is something very simple like collaborating containers that will be used if type is not registered in the container.
I think `parentInjector` here https://github.com/robotlegs/swiftsuspenders/blob/master/src/org/swiftsuspenders/Injector.as is good example of that.
